###############################################################################
#
# Makefile for a script (e.g. Python) VMtranslator project
#
# Students:
# Bart Simpson, ID 011111111, bart@cs.huji.ac.il
# Lisa Simpson, ID 022222222, lisa@cs.huji.ac.il
#
###############################################################################

# The executable for projects 7/8 is VMtranslator, so make sure the running 
# environment can execute it by changing permissions using chmod.
# Obviously, your project may be more complicated and require a different 
# makefile.

all:
	chmod a+x VMtranslator
